<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../ParcelJourney.Core/CompactJourneyReader.cs" Link="CompactJourneyReader.cs" />
    <Compile Include="../../ParcelJourney.Core/RealDatasetJourneyReader.cs" Link="RealDatasetJourneyReader.cs" />
    <Compile Include="../../ParcelJourney.Domain/Models.cs" Link="Models.cs" />
  </ItemGroup>
</Project>
